@startuml

object loginmenu
object Login
object SignUp
object User
object Child
object Username
object Password
object WatchList
object Movie
object Series
object Season
object Episode
object Genre
object Main
object Rating
object HasWatched
object SearchFunction
object ReleaseDecade
object RatingScore
object MediaName
object Media
object ReleaseYear
object Title
object MainMenu
object PlayMedia


loginmenu <-- Login
loginmenu <-- SignUp
loginmenu --> User
SearchFunction <-- RatingScore
SearchFunction <-- MediaName
SearchFunction <-- ReleaseDecade
Series *-- Season
Media --> Rating
Season *-- Episode
Main -- loginmenu
User *-- Username
User *-- Password
User --> MainMenu
MainMenu --> SearchFunction
MainMenu <-- PlayMedia : Method
User *-- Child
MainMenu *-- WatchList
MainMenu *-- HasWatched
HasWatched *-- Media
WatchList *-- Media
Media <|-- Movie
Media <|-- Series
Media --> Genre
SearchFunction <-- Media
ReleaseYear <-- Media
Media --> Title
@enduml
